services:
  api:
    container_name: open-ui-chat
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    ports:
      - "${PORT:-3080}:${PORT:-3080}"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: open-ui-chat-mongodb
    image: mongo
    command: mongod --noauth
    restart: always
    volumes:
      - ./data-node:/data/db




